-- Create ufc_master table
CREATE TABLE ufc_master (
    id SERIAL PRIMARY KEY,
    RedFighter VARCHAR(255),
    BlueFighter VARCHAR(255),
    RedOdds DECIMAL(10,2) NULL,
    BlueOdds DECIMAL(10,2) NULL,
    RedExpectedValue DECIMAL(10,4),
    BlueExpectedValue DECIMAL(10,4),
    Date VARCHAR(50),
    Location VARCHAR(255),
    Country VARCHAR(100),
    Winner VARCHAR(255),
    TitleBout BOOLEAN,
    WeightClass VARCHAR(100),
    Gender VARCHAR(20),
    NumberOfRounds INTEGER NULL,
    BlueCurrentLoseStreak INTEGER NULL,
    BlueCurrentWinStreak INTEGER NULL,
    BlueDraws INTEGER NULL,
    BlueAvgSigStrLanded DECIMAL(10,2) NULL,
    BlueAvgSigStrPct DECIMAL(10,4),
    BlueAvgSubAtt DECIMAL(10,2) NULL,
    BlueAvgTDLanded DECIMAL(10,2) NULL,
    BlueAvgTDPct DECIMAL(10,4),
    BlueLongestWinStreak INTEGER NULL,
    BlueLosses INTEGER NULL,
    BlueTotalRoundsFought INTEGER NULL,
    BlueTotalTitleBouts INTEGER NULL,
    BlueWinsByDecisionMajority INTEGER NULL,
    BlueWinsByDecisionSplit INTEGER NULL,
    BlueWinsByDecisionUnanimous INTEGER NULL,
    BlueWinsByKO INTEGER NULL,
    BlueWinsBySubmission INTEGER NULL,
    BlueWinsByTKODoctorStoppage INTEGER NULL,
    BlueWins INTEGER NULL,
    BlueStance VARCHAR(50),
    BlueHeightCms DECIMAL(10,2) NULL,
    BlueReachCms DECIMAL(10,2) NULL,
    BlueWeightLbs INTEGER NULL,
    RedCurrentLoseStreak INTEGER NULL,
    RedCurrentWinStreak INTEGER NULL,
    RedDraws INTEGER NULL,
    RedAvgSigStrLanded DECIMAL(10,2) NULL,
    RedAvgSigStrPct DECIMAL(10,4),
    RedAvgSubAtt DECIMAL(10,2) NULL,
    RedAvgTDLanded DECIMAL(10,2) NULL,
    RedAvgTDPct DECIMAL(10,4),
    RedLongestWinStreak INTEGER NULL,
    RedLosses INTEGER NULL,
    RedTotalRoundsFought INTEGER NULL,
    RedTotalTitleBouts INTEGER NULL,
    RedWinsByDecisionMajority INTEGER NULL,
    RedWinsByDecisionSplit INTEGER NULL,
    RedWinsByDecisionUnanimous INTEGER NULL,
    RedWinsByKO INTEGER NULL,
    RedWinsBySubmission INTEGER NULL,
    RedWinsByTKODoctorStoppage INTEGER NULL,
    RedWins INTEGER NULL,
    RedStance VARCHAR(50),
    RedHeightCms DECIMAL(10,2) NULL,
    RedReachCms DECIMAL(10,2) NULL,
    RedWeightLbs INTEGER NULL,
    RedAge INTEGER NULL,
    BlueAge INTEGER NULL,
    LoseStreakDif INTEGER NULL,
    WinStreakDif INTEGER NULL,
    LongestWinStreakDif INTEGER NULL,
    WinDif INTEGER NULL,
    LossDif INTEGER NULL,
    TotalRoundDif INTEGER NULL,
    TotalTitleBoutDif INTEGER NULL,
    KODif INTEGER NULL,
    SubDif INTEGER NULL,
    HeightDif DECIMAL(10,2) NULL,
    ReachDif DECIMAL(10,2) NULL,
    AgeDif INTEGER,
    SigStrDif DECIMAL(10,2) NULL,
    AvgSubAttDif DECIMAL(10,2) NULL,
    AvgTDDif DECIMAL(10,2) NULL,
    EmptyArena DECIMAL(10,2) NULL,
    BMatchWCRank DECIMAL(10,2) NULL,
    RMatchWCRank DECIMAL(10,2) NULL,
    RWFlyweightRank DECIMAL(10,2) NULL,
    RWFeatherweightRank DECIMAL(10,2) NULL,
    RWStrawweightRank DECIMAL(10,2) NULL,
    RWBantamweightRank DECIMAL(10,2) NULL,
    RHeavyweightRank DECIMAL(10,2) NULL,
    RLightHeavyweightRank DECIMAL(10,2) NULL,
    RMiddleweightRank DECIMAL(10,2) NULL,
    RWelterweightRank DECIMAL(10,2) NULL,
    RLightweightRank DECIMAL(10,2) NULL,
    RFeatherweightRank DECIMAL(10,2) NULL,
    RBantamweightRank DECIMAL(10,2) NULL,
    RFlyweightRank DECIMAL(10,2) NULL,
    RPFPRank DECIMAL(10,2) NULL,
    BWFlyweightRank DECIMAL(10,2) NULL,
    BWFeatherweightRank DECIMAL(10,2) NULL,
    BWStrawweightRank DECIMAL(10,2) NULL,
    BWBantamweightRank DECIMAL(10,2) NULL,
    BHeavyweightRank DECIMAL(10,2) NULL,
    BLightHeavyweightRank DECIMAL(10,2) NULL,
    BMiddleweightRank DECIMAL(10,2) NULL,
    BWelterweightRank DECIMAL(10,2) NULL,
    BLightweightRank DECIMAL(10,2) NULL,
    BFeatherweightRank DECIMAL(10,2) NULL,
    BBantamweightRank DECIMAL(10,2) NULL,
    BFlyweightRank DECIMAL(10,2) NULL,
    BPFPRank DECIMAL(10,2) NULL,
    BetterRank VARCHAR(50),
    Finish VARCHAR(100),
    FinishDetails VARCHAR(255),
    FinishRound DECIMAL(10,2) NULL,
    FinishRoundTime VARCHAR(20),
    TotalFightTimeSecs DECIMAL(10,2) NULL,
    RedDecOdds DECIMAL(10,2) NULL,
    BlueDecOdds DECIMAL(10,2) NULL,
    RSubOdds DECIMAL(10,2) NULL,
    BSubOdds DECIMAL(10,2) NULL,
    RKOOdds DECIMAL(10,2) NULL,
    BKOOdds DECIMAL(10,2) NULL
);

-- Create indexes for commonly queried columns
CREATE INDEX idx_red_fighter ON ufc_master(RedFighter);
CREATE INDEX idx_blue_fighter ON ufc_master(BlueFighter);
CREATE INDEX idx_date ON ufc_master(Date);
CREATE INDEX idx_weight_class ON ufc_master(WeightClass);
CREATE INDEX idx_winner ON ufc_master(Winner);

-- To run the Python script to import data into the ufc_master table, use the following command:
-- python ufc_master_iimport.py
