services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5778:5678" # 本機訪問編輯器 http://localhost:5778
    env_file:
      - .env # 讀取上一步建立的 .env
    environment:
      N8N_HOST: 0.0.0.0 # 在容器內綁到所有介面
      N8N_PROTOCOL: http # 內部使用 http；對外用 WEBHOOK_URL 的 https
      CHART_API_KEY: ${CHART_API_KEY} # 顯式帶入
      JINA_API_KEY: ${JINA_API_KEY} # 顯式帶入

      # ---- 開啟並安裝社群節點（JSON 陣列，放 npm 套件名）----
      # 請把下面的包名換成你要的社群節點（到 npm 搜 "n8n-nodes-xxxx"）
      N8N_COMMUNITY_PACKAGES: '["n8n-nodes-mcp","n8n-nodes-tavily"]'

      # （選）允許 Function/Code 節點引入外部套件
      # NODE_FUNCTION_ALLOW_EXTERNAL: axios,lodash,dayjs,airbnb,timer      

    volumes:
      - C:/n8n/n8n-data:/home/node/.n8n
      - C:/n8n/local-files:/files
