services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5778:5678" # 本機訪問編輯器 http://localhost:5778
    env_file:
      - .env # 讀取上一步建立的 .env
    environment:
      - N8N_HOST=0.0.0.0 # 在容器內綁到所有介面
      - N8N_PROTOCOL=http # 內部使用 http；對外用 WEBHOOK_URL 的 https
    volumes:
      - C:/n8n/n8n-data:/home/node/.n8n
      - C:/n8n/local-files:/files
