services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5778:5678"                 # 本機用 http://localhost:5778 開啟編輯器
    environment:
      - NODE_ENV=production
      - N8N_PORT=5678
      - GENERIC_TIMEZONE=Asia/Singapore
      - TZ=Asia/Singapore

      # ===== Tunnel（關鍵）=====
      - N8N_ENABLE_TUNNEL=true      # 開啟內建 Tunnel，產生公開的 HTTPS URL
      # 可選：自訂子網域（不保證一定可用；留空則隨機）
      - N8N_TUNNEL_SUBDOMAIN=mytest

      # 編輯器本機網址（給你在瀏覽器操作）
      - N8N_EDITOR_BASE_URL=http://localhost:5778

      # 建議移除以下本機設定，避免覆蓋 Tunnel 用的外部 URL
      # - N8N_PROTOCOL=http
      # - N8N_HOST=localhost
      # - WEBHOOK_URL=http://localhost:5778

      # 其他可選設定
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - NODE_FUNCTION_ALLOW_EXTERNAL=jsonwebtoken
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      # - N8N_BASIC_AUTH_ACTIVE=true
      # - N8N_BASIC_AUTH_USER=youruser
      # - N8N_BASIC_AUTH_PASSWORD=yourpass

    volumes:
      - C:/n8n/n8n-data:/home/node/.n8n   # 資料持久化（Windows 路徑）
      - C:/n8n/local-files:/files         #（可選）共享檔案
